### ISSUE TITLE
Indent setting to work with `mdformat-mkdocs`

### ISSUE THREAD

**Issue by CBroz1** [hukkin/mdformat-toc#12]
In my current pre-commit file, I'm running mdformat twice, once with `toc` and once with `mkdocs` so that the lists generated have 4-space indents to comply with the mkdocs norm. 

<details>
<summary>Current pre-commit</summary>

```yaml
  - repo: https://github.com/executablebooks/mdformat
    rev: 0.7.16
    hooks:
      - id: mdformat
        name: Format Markdown
        entry: mdformat # Executable to run, with fixed options
        language: python
        types: [markdown]
        args: [--wrap, "80", --number]
        additional_dependencies:
          - mdformat-toc

  # run twice so that the TOC is updated to 4-indent
  - repo: https://github.com/executablebooks/mdformat
    rev: 0.7.16
    hooks:
      - id: mdformat
        name: Format Markdown
        entry: mdformat # Executable to run, with fixed options
        language: python
        types: [markdown]
        args: [--wrap, "80", --number]
        additional_dependencies:
          - mdformat-mkdocs
```
</details>

Is it possible to add `--indent X` to `Opts`? Would the maintenance team be interested in a PR?
